### PR TITLE
Uplift third_party/tt-mlir to  2024-10-28

### PR DESCRIPTION
**Pull request by vmilosevic**
This PR uplifts the third_party/tt-mlir to the

### CODE REVIEW

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Comment by vmilosevic** [comment]
@AleksKnezevic there was an LLVM change in tt-mlir that cause incompatibility with old toolchain, this is probably the same thing.
We can do it manually, but I'm also making a change in the docker build to be a part of a workflow (see https://github.com/tenstorrent/tt-mlir/pull/928#pullrequestreview-2375280337) so you can also wait until I do the similar change on tt-xla

**Comment by AleksKnezevic** [comment]
@uazizTT you manually kicked off a docker build, right?

**Comment by uazizTT** [comment]
> @uazizTT you manually kicked off a docker build, right?

Yes I did but it failed due to out of space error. 
https://github.com/tenstorrent/tt-xla/actions/runs/11368786811

I discussed with @vmilosevic and he suggested that Github runners don't have enough space, so we can modify _build-image.yml_ script to run the build on _n300_ machines. I just opened a PR for it:
https://github.com/tenstorrent/tt-xla/pull/36

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Comment by uazizTT** [comment]
`/__w/tt-xla/tt-xla/third_party/tt-mlir/src/tt-mlir/lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp:119:21: error: no member named 'LValueType' in namespace 'mlir::emitc'; did you mean 'OpaqueType'?`

@vmilosevic It is still trying to build with the old environment.

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]

**Pull request merged**
